// =============================================================================
// AUTO-GENERATED by scripts/abi-extractor/generate-types.js
// DO NOT EDIT MANUALLY — re-run the ABI extractor to regenerate.
//
// This is a sample type definition showing the pattern used for all contracts.
// When the ABI extractor runs, it will overwrite this file with types derived
// from the actual compiled contract ABI.
// =============================================================================

/** Generic Result type for contract calls */
export type Result<T, E> = { ok: true; value: T } | { ok: false; error: E };

/** Contract metadata */
export const LendingCoreMetadata = {
  contractName: "lending-core",
  wasmHash: "",
  version: "",
  extractedAt: "",
} as const;

// ---------------------------------------------------------------------------
// Struct types (from contract spec)
// ---------------------------------------------------------------------------

/** A user's lending position */
export interface Position {
  collateralAmount: bigint;
  debtAmount: bigint;
  lastUpdated: bigint;
}

/** Configuration for an asset in the lending protocol */
export interface AssetConfig {
  collateralFactor: bigint;
  liquidationThreshold: bigint;
  reserveFactor: bigint;
  maxSupply: bigint;
  maxBorrow: bigint;
}

/** Computed position data for a user */
export interface UserPosition {
  user: string;
  collateralValue: bigint;
  debtValue: bigint;
  healthFactor: bigint;
}

/** Protocol-wide configuration */
export interface ProtocolConfig {
  admin: string;
  oracle: string | null;
  debtCeiling: bigint;
  minBorrowAmount: bigint;
  liquidationThresholdBps: bigint;
}

// ---------------------------------------------------------------------------
// Enum types
// ---------------------------------------------------------------------------

/** Protocol pause state */
export enum PauseState {
  Active = 0,
  Paused = 1,
}

/** Types of lending operations */
export enum OperationType {
  Deposit = 0,
  Withdraw = 1,
  Borrow = 2,
  Repay = 3,
  Liquidation = 4,
}

// ---------------------------------------------------------------------------
// Error types
// ---------------------------------------------------------------------------

/** Contract error codes */
export enum CommonError {
  Unauthorized = 1,
  InvalidAmount = 2,
  InsufficientBalance = 3,
  ExceedsLimit = 4,
  ProtocolPaused = 5,
  OracleNotSet = 6,
  InvalidConfiguration = 7,
  ReentrancyDetected = 8,
}

// ---------------------------------------------------------------------------
// Client interface
// ---------------------------------------------------------------------------

/** Type-safe client interface for the lending-core contract */
export interface LendingCoreClient {
  /** Initialize the lending protocol with an admin and debt ceiling */
  initialize(admin: string, debtCeiling: bigint): Promise<Result<void, CommonError>>;

  /** Get the current protocol admin address */
  getAdmin(): Promise<string | null>;

  /** Get a user's current lending position */
  getPosition(user: string): Promise<Position | null>;

  /** Update a user's lending position */
  updatePosition(user: string, position: Position): Promise<Result<void, CommonError>>;
}

/** Contract function names */
export const LendingCoreFunctions = {
  initialize: "initialize",
  getAdmin: "get_admin",
  getPosition: "get_position",
  updatePosition: "update_position",
} as const;
